local bpc = require("bpc")

local record_type_enum = bpc.enum("RecordType")
    :variant(1, "A", "IPv4 Address")
    :variant(2, "NS", "Name Server")
    :variant(5, "CNAME", "Canonical Name")
    :build(16)

local class_enum = bpc.enum("Class")
    :variant(1, "IN", "Internet")
    :variant(3, "CH", "CHAOS")
    :build(16)

local header_layout = bpc.layout("Header")
    :field("transaction_id", 16)
    :field("flags", 16)
    :field("questions", 16)
    :field("answer_rrs", 16)
    :field("authority_rrs", 16)
    :field("additional_rrs", 16)
    :build()

local record_layout = bpc.layout("Record")
    :field("name_ptr", 16)
    :field_enum("type", record_type_enum)
    :field_enum("class", class_enum)
    :field("ttl", 32)
    :field("data_length", 16)
    :field_var("data", "data_length", "bytes")
    :build()

return bpc.layout("DnsPacket")
    :field_layout("header", header_layout)
    :field_layout("query_record", record_layout)
    :build()
